### ISSUE TITLE
marahon container don't have web ui

### ISSUE THREAD

**Issue by a93ushakov** [mesosphere/docker-containers#39]
In one `docker` container I had installed through your `debian` repo `mesos` and `marathon`.

In one `tmux` pane I had launched `mesos-master --registry=in_memory`  - web ui works on 5050 port, in second pane I try to launch `marathon`, but web ui dont work here.

Can you help?

**Comment by ssk2** [comment]
Hey @a93ushakov - you will need ZooKeeper too for Marathon to work (the logs should indicate that it is trying to connect to a ZooKeeper instance and failing). This tutorial might help: https://open.mesosphere.com/getting-started/install/.

**Comment by a93ushakov** [comment]
As I understand in your `apt` repo is absent `zookeeper` package? It should be installed through `debian` repo?

**Comment by a93ushakov** [comment]
And, maybe exist ready for use `docker` containers that allow without configuration start work with `marathon` on one laptop?

**Comment by ssk2** [comment]
ZooKeeper isn't a package we provide - you can get it through the ordinary Debian repos (https://packages.debian.org/search?keywords=zookeeper) or from Cloudera. 

We're working on a more up to date Vagrant image that will let you use Marathon on one computer but for now, you can try using [playa-mesos](https://github.com/mesosphere/playa-mesos). We don't provide Docker images for Marathon + Mesos + ZooKeeper because generally we like to keep just one process running per Docker container.
