### ISSUE TITLE
Why is mesos-slave-dind not kept up to date?

### ISSUE THREAD

**Issue by yfinkelstein** [mesosphere/docker-containers#43]
https://hub.docker.com/r/mesosphere/mesos-slave-dind/
is not maintained up to date. In the mean time, mesosphere/mesos-slave does not include  docker binary which causes a bund of problems. In order to make host's /usr/bin/docker accessible from within the slave docker one needs to bind-mount /lib64 and other system directories which imposes compatibility constrains on the host OS.  mesos-slave-dind is really the way to go, but it has to be maintained up to date. In fact, it looks like the Dockerfile used to build it has been removed in github:
https://github.com/mesosphere/docker-containers/tree/master/mesos-slave-dind

**Comment by yfinkelstein** [comment]
This merge 
https://github.com/mesosphere/docker-containers/commit/58f5b988f33a429e3f119cac13b46f30188b0163

removed mesos-slave-dind without any comments. I wonder why?

**Comment by karlkfi** [comment]
mesos-slave-dind was extracted to its own repo: https://github.com/mesosphere/mesos-slave-dind

Looks like the link on dockerhub wasn't updated when that happened. I'll fix that.

Unlike the other mesos docker images (maintained by the core mesos team), the mesos-slave-dind image was being maintained by the kubernetes-mesos team, for use in the kubernetes local dev/ci environment (https://github.com/kubernetes/kubernetes/blob/master/cluster/mesos/docker/docker-compose.yml#L33). 

Unfortunately, because it's maintained by a framework team and not the core team, it's never going to be quite as up to date as the other mesos docker images... There's not much way around that other than donating it to the core team for them to maintain, even tho they don't use it. There's definitely some testing and CI work that could be done to automate the process a little better, but it hasn't been high on the priority list. I usually just plug it into https://github.com/karlkfi/mesos-compose-dind and fire it up to make sure it comes up.  TBH, you're the first person to complain!

**I'd love to hear more about your use case.** Generally, I consider mesos-slave-dind only really useful for testing and development. I wouldn't recommend using dind in production. Mesos itself isn't really designed to be containerized, ironically.

Anyway, I'll go ahead and update it. But we still need to figure out a long term solution. FWIW, I would definitely take PRs on https://github.com/mesosphere/mesos-slave-dind

**Comment by karlkfi** [comment]
Just pushed a new release for github and dockerhub: mesosphere/mesos-slave-dind:0.2.4_mesos-0.27.2_docker-1.8.2_ubuntu-14.04.4
